// <auto-generated />
using System;
using HidroSafe.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace HidroSafe.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250608215211_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HidroSafe.API.Models.EstacaoMonitoramento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInstalacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("ESTACOES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataInstalacao = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Localizacao = "Rua do Córrego, 123",
                            Nome = "Estação Rio do Meio"
                        });
                });

            modelBuilder.Entity("HidroSafe.API.Models.LeituraDistancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<double>("DistanciaMargemCm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("EstacaoMonitoramentoId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("EstacaoMonitoramentoId");

                    b.ToTable("LEITURAS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataHora = new DateTime(2025, 6, 8, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            DistanciaMargemCm = 18.5,
                            EstacaoMonitoramentoId = 1
                        });
                });

            modelBuilder.Entity("HidroSafe.API.Models.LeituraDistancia", b =>
                {
                    b.HasOne("HidroSafe.API.Models.EstacaoMonitoramento", "EstacaoMonitoramento")
                        .WithMany("Leituras")
                        .HasForeignKey("EstacaoMonitoramentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstacaoMonitoramento");
                });

            modelBuilder.Entity("HidroSafe.API.Models.EstacaoMonitoramento", b =>
                {
                    b.Navigation("Leituras");
                });
#pragma warning restore 612, 618
        }
    }
}
